**Connor's DevOps Experience Cheat Sheet:**

- **Full Name:** Connor Li
- **Location:** Based in Toronto, Ontario, Canada
- **Professional Background:**
  - Senior DevOps Engineer at TD (since August 2022)
  - DevOps Engineer at TD (August 2021 - July 2022)
- **Key DevOps Skills:**
  - DevOps
  - Vault
  - SaltStack
  - Terraform
  - Microsoft Azure
  - Jenkins
  - Java
  - Python
- **Notable DevOps Projects:**
  - Led the development of a KPI Dashboard for DevOps analytics and reporting.
  - Upgraded Terraform infrastructure in Azure.
  - Provided critical debugging support for upgrading GitHub.
  - Enforced code coverage standards for the Enterprise DevOps Pipeline (EDP) by integrating SonarQube and updated code repositories to enhance code coverage analysis for both the EDP XL and GT projects.
- **Experience:** Transitioned from teaching assistant roles to a career in DevOps engineering.
- **Personal Website:** [connorli.com](http://connorli.com)
